package vista;
import java.awt.BorderLayout;
import modelo.Iconodesistema;
import modelo.Usuario;
public class MenuPrincipal extends javax.swing.JFrame {

    private Usuario usuario;
    public MenuPrincipal(Usuario usuario) {
        Iconodesistema.setIcon(this);
        initComponents();
        this.usuario = usuario;
        configurarPorRol();
        Inicio();
    }

    private void configurarPorRol() {
        if ("usuario".equalsIgnoreCase(usuario.getRol())) {
            btnUsuarios.setEnabled(false);
        }
    }
 private void Inicio(){
        Home h=new Home();
        h.setSize(982,740);
        h.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(h,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        }

    private MenuPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound3 = new modelo.JpanelRound();
        contenedor = new javax.swing.JPanel();
        jpanelRound2 = new modelo.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnCategoria = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnCarreras = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnAula = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnUsuarios = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnMantenimiento = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnActivos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnDepreciacion = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnRegistroActivos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnReportes = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnTransferencia = new RSMaterialComponent.RSButtonMaterialIconDos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Activos Fijos");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpanelRound3.setRoundBottomLeft(25);
        jpanelRound3.setRoundBottomRight(25);
        jpanelRound3.setRoundTopLeft(25);
        jpanelRound3.setRoundTopRight(25);

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(999, 775));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jpanelRound2.setBackground(new java.awt.Color(14, 76, 117));
        jpanelRound2.setRoundBottomLeft(25);
        jpanelRound2.setRoundBottomRight(25);
        jpanelRound2.setRoundTopLeft(25);
        jpanelRound2.setRoundTopRight(25);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACTIVOS FIJOS");

        btnCategoria.setBackground(new java.awt.Color(14, 76, 117));
        btnCategoria.setText("CATEGORIA");
        btnCategoria.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnCategoria.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnCarreras.setBackground(new java.awt.Color(14, 76, 117));
        btnCarreras.setText("CARRERAS");
        btnCarreras.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnCarreras.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        btnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrerasActionPerformed(evt);
            }
        });

        btnAula.setBackground(new java.awt.Color(14, 76, 117));
        btnAula.setText("AULAS");
        btnAula.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnAula.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        btnAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAulaActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(14, 76, 117));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnUsuarios.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_TAB);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnMantenimiento.setBackground(new java.awt.Color(14, 76, 117));
        btnMantenimiento.setText("MANTENIMIENTO");
        btnMantenimiento.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnMantenimiento.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON_ADD);
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(14, 76, 117));
        btnSalir.setText("CERRAR SESION");
        btnSalir.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActivos.setBackground(new java.awt.Color(14, 76, 117));
        btnActivos.setText("ACTIVOS");
        btnActivos.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnActivos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LAPTOP);
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });

        btnDepreciacion.setBackground(new java.awt.Color(14, 76, 117));
        btnDepreciacion.setText("DEPRECIACION");
        btnDepreciacion.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnDepreciacion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_LIST);
        btnDepreciacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepreciacionActionPerformed(evt);
            }
        });

        btnRegistroActivos.setBackground(new java.awt.Color(14, 76, 117));
        btnRegistroActivos.setText("REGISTRAR ACTIVOS");
        btnRegistroActivos.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnRegistroActivos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        btnRegistroActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActivosActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(14, 76, 117));
        btnReportes.setText("REPORTES");
        btnReportes.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_UPLOAD);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnTransferencia.setBackground(new java.awt.Color(14, 76, 117));
        btnTransferencia.setText("TRANSFERENCIA");
        btnTransferencia.setBackgroundHover(new java.awt.Color(50, 130, 181));
        btnTransferencia.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.IMPORT_EXPORT);
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistroActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDepreciacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistroActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepreciacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
    btnAula.setSelected(false);    
    btnMantenimiento.setSelected(false);
    btnRegistroActivos.setSelected(false);
    btnCarreras.setSelected(false);
    btnDepreciacion.setSelected(false);
    btnCategoria.setSelected(false);
    btnUsuarios.setSelected(false);
    btnActivos.setSelected(true);
    btnReportes.setSelected(false);
    btnTransferencia.setSelected(false);
    
    Activos af=new Activos();
    af.setSize(982,740);
    af.setLocation(0,0);
    contenedor.removeAll();
    contenedor.add(af,BorderLayout.CENTER);
    contenedor.revalidate();
    contenedor.repaint();
    }//GEN-LAST:event_btnActivosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        Login m=new Login();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
       btnCarreras.setSelected(false);
       btnAula.setSelected(false);
       btnRegistroActivos.setSelected(false);
       btnMantenimiento.setSelected(true);
       btnCategoria.setSelected(false);
       btnActivos.setSelected(false);
       btnUsuarios.setSelected(false);
       btnDepreciacion.setSelected(false);
       btnReportes.setSelected(false);
       btnTransferencia.setSelected(false);
       
       Mantenimiento m=new Mantenimiento();
       m.setSize(982,740);
       m.setLocation(0,0);
       contenedor.removeAll();
       contenedor.add(m,BorderLayout.CENTER);
       contenedor.revalidate();
       contenedor.repaint();
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
    btnAula.setSelected(false);  
    btnMantenimiento.setSelected(false);
    btnRegistroActivos.setSelected(false);
    btnCarreras.setSelected(false);
    btnActivos.setSelected(false);
    btnUsuarios.setSelected(true);
    btnCategoria.setSelected(false);
    btnDepreciacion.setSelected(false);
    btnReportes.setSelected(false);
    btnTransferencia.setSelected(false);
    
    Usuarios u=new Usuarios();
    u.setSize(982,740);
    u.setLocation(0,0);
    contenedor.removeAll();
    contenedor.add(u,BorderLayout.CENTER);
    contenedor.revalidate();
    contenedor.repaint();    
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAulaActionPerformed
        btnAula.setSelected(true);
        btnMantenimiento.setSelected(false);
        btnCarreras.setSelected(false);
        btnUsuarios.setSelected(false);
        btnRegistroActivos.setSelected(false);
        btnCategoria.setSelected(false);
        btnActivos.setSelected(false);
        btnDepreciacion.setSelected(false);
        btnReportes.setSelected(false);
        btnTransferencia.setSelected(false);
        
        Aulas d=new Aulas();
        d.setSize(982,740);
        d.setLocation(0,0);
        contenedor.removeAll();
        contenedor.add(d,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnAulaActionPerformed

    private void btnRegistroActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActivosActionPerformed
       btnCarreras.setSelected(false);
       btnAula.setSelected(false);
       btnUsuarios.setSelected(false);
       btnMantenimiento.setSelected(false);
       btnRegistroActivos.setSelected(true);
       btnCategoria.setSelected(false);
       btnActivos.setSelected(false);
       btnDepreciacion.setSelected(false);
       btnReportes.setSelected(false);
       btnTransferencia.setSelected(false);
        
       R_Activos ra=new R_Activos();
       ra.setSize(982,740);
       ra.setLocation(0,0);
       contenedor.removeAll();
       contenedor.add(ra,BorderLayout.CENTER);
       contenedor.revalidate();
       contenedor.repaint();
    }//GEN-LAST:event_btnRegistroActivosActionPerformed

    private void btnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrerasActionPerformed
        btnCarreras.setSelected(true);
        btnAula.setSelected(false);
        btnUsuarios.setSelected(false);
        btnRegistroActivos.setSelected(false);
        btnMantenimiento.setSelected(false);
        btnCategoria.setSelected(false);
        btnActivos.setSelected(false);
        btnDepreciacion.setSelected(false);
        btnReportes.setSelected(false);
        btnTransferencia.setSelected(false);
        
        Carreras c=new Carreras();
        c.setSize(982,740);
        c.setLocation(0,0);
        contenedor.removeAll();
        contenedor.add(c,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnCarrerasActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
    btnAula.setSelected(false);
    btnMantenimiento.setSelected(false);
    btnRegistroActivos.setSelected(false);
    btnCarreras.setSelected(false);
    btnCategoria.setSelected(true);
    btnDepreciacion.setSelected(false);
    btnUsuarios.setSelected(false);
    btnActivos.setSelected(false);
    btnReportes.setSelected(false);
    btnTransferencia.setSelected(false);
    
    Categorias c=new Categorias();
    c.setSize(982,740);
    c.setLocation(0,0);
    contenedor.removeAll();
    contenedor.add(c,BorderLayout.CENTER);
    contenedor.revalidate();
    contenedor.repaint();
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnDepreciacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepreciacionActionPerformed
    btnAula.setSelected(false);
    btnMantenimiento.setSelected(false);
    btnRegistroActivos.setSelected(false);
    btnCarreras.setSelected(false);
    btnCategoria.setSelected(false);
    btnActivos.setSelected(false);
    btnUsuarios.setSelected(false);
    btnDepreciacion.setSelected(true);
    btnReportes.setSelected(false);
    btnTransferencia.setSelected(false);
    
    Depreciacion dp=new Depreciacion();
    dp.setSize(982,740);
    dp.setLocation(0,0);
    contenedor.removeAll();
    contenedor.add(dp,BorderLayout.CENTER);
    contenedor.revalidate();
    contenedor.repaint();
    }//GEN-LAST:event_btnDepreciacionActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        btnAula.setSelected(false);
        btnMantenimiento.setSelected(false);
        btnRegistroActivos.setSelected(false);
        btnCarreras.setSelected(false);
        btnCategoria.setSelected(false);
        btnActivos.setSelected(false);
        btnDepreciacion.setSelected(false);
        btnUsuarios.setSelected(false);
        btnReportes.setSelected(true);
        btnTransferencia.setSelected(false);
        
        Reportes t=new Reportes();
        t.setSize(982,740);
        t.setLocation(0,0);
        contenedor.removeAll();
        contenedor.add(t,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
       btnCarreras.setSelected(false);
       btnAula.setSelected(false);
       btnRegistroActivos.setSelected(false);
       btnMantenimiento.setSelected(false);
       btnCategoria.setSelected(false);
       btnActivos.setSelected(false);
       btnUsuarios.setSelected(false);
       btnDepreciacion.setSelected(false);
       btnReportes.setSelected(false);
       btnTransferencia.setSelected(true);
       
       Transferencias t=new Transferencias();
       t.setSize(982,740);
       t.setLocation(0,0);
       contenedor.removeAll();
       contenedor.add(t,BorderLayout.CENTER);
       contenedor.revalidate();
       contenedor.repaint();
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static RSMaterialComponent.RSButtonMaterialIconDos btnActivos;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnAula;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnCarreras;
    private RSMaterialComponent.RSButtonMaterialIconDos btnCategoria;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnDepreciacion;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnMantenimiento;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnRegistroActivos;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnReportes;
    private RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnTransferencia;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnUsuarios;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private modelo.JpanelRound jpanelRound2;
    private modelo.JpanelRound jpanelRound3;
    // End of variables declaration//GEN-END:variables
}
